-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."categories" add column "icon" text
--  not null default 'https://res.cloudinary.com/ddkybdc5n/image/upload/v1684311717/EAII-Products/hospital_sz4ku5.png';
